server:
  port: 8081
spring:
  application:
    name: user-service

address.service.url: http://address-service/address/user/{userId}
eureka:
  client:
    service-url:
      - defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true