server:
  port: 8082
spring:
  application:
    name: address-service

eureka:
  client:
    service-url:
      - defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true